apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
spec:
  selector:
    matchLabels:
      app: api-node
  template:
    metadata:
      labels:
        app: api-node
    spec:
      containers:
      - name: api-node
        image: elmpl/api-node
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-node
spec:
  type: LoadBalancer
  selector:
    app: api-node
  ports:
  - port: 3000
    targetPort: 3000
